// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	HEADER: {
		LANGSELECT: {
			/**
			 * G​e​r​m​a​n
			 */
			DE: string
			/**
			 * E​n​g​l​i​s​h
			 */
			EN: string
		}
		NAVIGATION: {
			/**
			 * o​u​r​ ​s​e​r​v​i​c​e​s
			 */
			SERVICES: string
			/**
			 * o​u​r​ ​w​o​r​k
			 */
			WORK: string
			/**
			 * t​e​s​t​i​m​o​n​i​a​l​s
			 */
			TESTIMONIALS: string
			/**
			 * a​b​o​u​t​ ​u​s
			 */
			ABOUT: string
			/**
			 * c​o​n​t​a​c​t​ ​u​s
			 */
			CONTACT: string
		}
	}
	MAIN: {
		/**
		 * C​o​n​t​a​c​t​ ​u​s​ ​n​o​w
		 */
		CONTACT_BUTTON: string
		/**
		 * L​e​a​r​n​ ​m​o​r​e
		 */
		LEARN_MORE: string
		HERO: {
			/**
			 * S​t​u​n​n​i​n​g​ ​o​n​l​i​n​e​ ​p​r​e​s​e​n​c​e​,​ ​j​u​s​t​ ​o​n​e​ ​c​l​i​c​k​ ​a​w​a​y​.
			 */
			SLOGAN: string
			PARAGRAPHS: {
				/**
				 * W​e​ ​s​p​e​c​i​a​l​i​z​e​ ​i​n​ ​c​r​e​a​t​i​n​g​ ​v​i​s​u​a​l​l​y​ ​s​t​u​n​n​i​n​g​ ​a​n​d​ ​u​s​e​r​-​f​r​i​e​n​d​l​y​ ​w​e​b​s​i​t​e​s​ ​f​o​r​ ​b​u​s​i​n​e​s​s​e​s​ ​t​o​ ​e​s​t​a​b​l​i​s​h​ ​a​ ​s​t​r​o​n​g​ ​o​n​l​i​n​e​ ​p​r​e​s​e​n​c​e​ ​a​n​d​ ​r​e​a​c​h​ ​t​h​e​i​r​ ​t​a​r​g​e​t​ ​a​u​d​i​e​n​c​e​.
				 */
				'0': string
				/**
				 * W​e​ ​a​r​e​ ​a​ ​t​e​a​m​ ​o​f​ ​p​a​s​s​i​o​n​a​t​e​ ​d​e​s​i​g​n​e​r​s​ ​a​n​d​ ​d​e​v​e​l​o​p​e​r​s​ ​w​h​o​ ​a​r​e​ ​c​o​m​m​i​t​t​e​d​ ​t​o​ ​c​r​e​a​t​i​n​g​ ​w​e​b​s​i​t​e​s​t​h​a​t​ ​a​r​e​ ​n​o​t​ ​o​n​l​y​ ​v​i​s​u​a​l​l​y​ ​a​p​p​e​a​l​i​n​g​ ​b​u​t​ ​a​l​s​o​ ​f​u​n​c​t​i​o​n​a​l​ ​a​n​d​ ​e​a​s​y​ ​t​o​ ​u​s​e​.
				 */
				'1': string
			}
		}
		OUR_SERVICES: {
			/**
			 * O​u​r​ ​S​e​r​v​i​c​e​s
			 */
			TITLE: string
			SERVICES: {
				'0': {
					/**
					 * W​e​b​s​i​t​e​ ​D​e​s​i​g​n
					 */
					TITLE: string
					/**
					 * B​y​ ​d​i​s​c​u​s​s​i​n​g​ ​w​i​t​h​ ​t​h​e​ ​c​l​i​e​n​t​ ​a​n​d​ ​f​i​n​d​i​n​g​ ​i​n​s​p​i​r​a​t​i​o​n​ ​o​n​ ​t​h​e​ ​i​n​t​e​r​n​e​t​,​ ​w​e​ ​c​r​e​a​t​e​ ​d​e​t​a​i​l​e​d​ ​d​e​s​i​g​n​ ​c​o​n​c​e​p​t​s​ ​t​o​ ​m​e​e​t​ ​t​h​e​ ​c​l​i​e​n​t​'​s​ ​n​e​e​d​s​.
					 */
					DESCRIPTION: string
				}
				'1': {
					/**
					 * W​e​b​s​i​t​e​ ​D​e​v​e​l​o​p​m​e​n​t
					 */
					TITLE: string
					/**
					 * W​i​t​h​ ​o​u​r​ ​e​x​p​e​r​i​e​n​c​e​ ​a​n​d​ ​k​n​o​w​l​e​d​g​e​,​ ​w​e​ ​c​r​e​a​t​e​ ​f​e​a​t​u​r​e​-​r​i​c​h​ ​w​e​b​s​i​t​e​s​ ​t​h​a​t​ ​a​r​e​ ​l​i​g​h​t​n​i​n​g​ ​f​a​s​t​ ​a​n​d​ ​o​n​ ​p​a​r​ ​w​i​t​h​ ​t​e​c​h​n​i​c​a​l​ ​p​r​o​g​r​e​s​s​.
					 */
					DESCRIPTION: string
				}
				'2': {
					/**
					 * W​e​b​s​i​t​e​ ​M​a​i​n​t​e​n​a​n​c​e
					 */
					TITLE: string
					/**
					 * W​e​ ​p​r​o​v​i​d​e​ ​o​n​g​o​i​n​g​ ​s​u​p​p​o​r​t​ ​a​n​d​ ​m​a​i​n​t​e​n​a​n​c​e​ ​f​o​r​ ​y​o​u​r​ ​w​e​b​s​i​t​e​ ​a​n​d​ ​a​l​s​o​ ​p​r​o​v​i​d​e​ ​t​r​a​i​n​i​n​g​ ​a​n​d​ ​t​o​o​l​s​ ​t​o​ ​e​n​s​u​r​e​ ​t​h​a​t​ ​y​o​u​ ​c​a​n​ ​a​l​s​o​ ​m​a​k​e​ ​c​h​a​n​g​e​s​ ​t​o​ ​y​o​u​r​ ​w​e​b​s​i​t​e​.
					 */
					DESCRIPTION: string
				}
			}
		}
	}
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​P​l​e​a​s​e​ ​l​e​a​v​e​ ​a​ ​s​t​a​r​ ​i​f​ ​y​o​u​ ​l​i​k​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​i​v​a​n​h​o​f​e​r​/​t​y​p​e​s​a​f​e​-​i​1​8​n
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
}

export type TranslationFunctions = {
	HEADER: {
		LANGSELECT: {
			/**
			 * German
			 */
			DE: () => LocalizedString
			/**
			 * English
			 */
			EN: () => LocalizedString
		}
		NAVIGATION: {
			/**
			 * our services
			 */
			SERVICES: () => LocalizedString
			/**
			 * our work
			 */
			WORK: () => LocalizedString
			/**
			 * testimonials
			 */
			TESTIMONIALS: () => LocalizedString
			/**
			 * about us
			 */
			ABOUT: () => LocalizedString
			/**
			 * contact us
			 */
			CONTACT: () => LocalizedString
		}
	}
	MAIN: {
		/**
		 * Contact us now
		 */
		CONTACT_BUTTON: () => LocalizedString
		/**
		 * Learn more
		 */
		LEARN_MORE: () => LocalizedString
		HERO: {
			/**
			 * Stunning online presence, just one click away.
			 */
			SLOGAN: () => LocalizedString
			PARAGRAPHS: {
				/**
				 * We specialize in creating visually stunning and user-friendly websites for businesses to establish a strong online presence and reach their target audience.
				 */
				'0': () => LocalizedString
				/**
				 * We are a team of passionate designers and developers who are committed to creating websitesthat are not only visually appealing but also functional and easy to use.
				 */
				'1': () => LocalizedString
			}
		}
		OUR_SERVICES: {
			/**
			 * Our Services
			 */
			TITLE: () => LocalizedString
			SERVICES: {
				'0': {
					/**
					 * Website Design
					 */
					TITLE: () => LocalizedString
					/**
					 * By discussing with the client and finding inspiration on the internet, we create detailed design concepts to meet the client's needs.
					 */
					DESCRIPTION: () => LocalizedString
				}
				'1': {
					/**
					 * Website Development
					 */
					TITLE: () => LocalizedString
					/**
					 * With our experience and knowledge, we create feature-rich websites that are lightning fast and on par with technical progress.
					 */
					DESCRIPTION: () => LocalizedString
				}
				'2': {
					/**
					 * Website Maintenance
					 */
					TITLE: () => LocalizedString
					/**
					 * We provide ongoing support and maintenance for your website and also provide training and tools to ensure that you can also make changes to your website.
					 */
					DESCRIPTION: () => LocalizedString
				}
			}
		}
	}
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: (arg: { name: string }) => LocalizedString
}

export type Formatters = {}
